### ISSUE TITLE
同时制定字幕输出格式

### ISSUE THREAD

**Issue by Asphelzhn** [jinsongpan/video-srt-command#1]
请问如何指定多个生成字幕的格式（srt,lrc,txt）？

**Comment by jinsongpan** [comment]
在config.ini里修改字段“outputType”就可以了。但是每次运行只能指定一种格式

**Comment by Asphelzhn** [comment]
> 在config.ini里修改字段“outputType”就可以了。但是每次运行只能指定一种格式

希望能支持一下多种格式同时输出，感谢

**Comment by jinsongpan** [comment]
> > 在config.ini里修改字段“outputType”就可以了。但是每次运行只能指定一种格式
> 
> 希望能支持一下多种格式同时输出，感谢

这个需求我可以先记下来

**Comment by Asphelzhn** [comment]
> > > 在config.ini里修改字段“outputType”就可以了。但是每次运行只能指定一种格式
> > 
> > 
> > 希望能支持一下多种格式同时输出，感谢
> 
> 这个需求我可以先记下来


2020/09/17 17:18:25 运行过程中出现未知错误: SDK.ServerError                      ErrorCode: MissingAccessKeyId                                                    Recommend: https://error-center.aliyun.com/status/search?Keyword=MissingAccessKe yId&source=PopGw                                                                 RequestId: 44354D2A-F514-4B6D-B837-CCABF3013E11                                  Message: AccessKeyId is mandatory for this action.
--
配置中已经添加了accessKeyId，但还是报错，请问如何解决

**Comment by jinsongpan** [comment]
> > > > 在config.ini里修改字段“outputType”就可以了。但是每次运行只能指定一种格式
> > > 
> > > 
> > > 希望能支持一下多种格式同时输出，感谢
> > 
> > 
> > 这个需求我可以先记下来
> 
> ## 2020/09/17 17:18:25 运行过程中出现未知错误: SDK.ServerError ErrorCode: MissingAccessKeyId Recommend: https://error-center.aliyun.com/status/search?Keyword=MissingAccessKe yId&source=PopGw RequestId: 44354D2A-F514-4B6D-B837-CCABF3013E11 Message: AccessKeyId is mandatory for this action.
> 配置中已经添加了accessKeyId，但还是报错，请问如何解决

我测了下没问题。看你的报错应该不是代码的问题，是config.ini配置的问题：你把[AliyunOSS]下我没删干净的的endpoint字段改成自己的，试下先

**Comment by jinsongpan** [comment]
> > > > > 在config.ini里修改字段“outputType”就可以了。但是每次运行只能指定一种格式
> > > > 
> > > > 
> > > > 希望能支持一下多种格式同时输出，感谢
> > > 
> > > 
> > > 这个需求我可以先记下来
> > 
> > 
> > ## 2020/09/17 17:18:25 运行过程中出现未知错误: SDK.ServerError ErrorCode: MissingAccessKeyId Recommend: https://error-center.aliyun.com/status/search?Keyword=MissingAccessKe yId&source=PopGw RequestId: 44354D2A-F514-4B6D-B837-CCABF3013E11 Message: AccessKeyId is mandatory for this action.
> > 配置中已经添加了accessKeyId，但还是报错，请问如何解决
> 
> 我测了下没问题。看你的报错应该不是代码的问题，是config.ini配置的问题：你把[AliyunOSS]下我没删干净的的endpoint字段改成自己的，试下先

确定是识别服务的配置问题
